### PR TITLE
Feature/31/feature gate jitter

### LINKED ISSUE #31: Gate `rand` behind a feature gate by making `Jitter` optional
Heya :wave:,

I'm writing a library that targets the web, and would like to be able to turn off dependencies as much as possible -- mainly to reduce compilation times as well as load times on web pages. One of these is `rand`, which is only used by `Jitter` when that is required.

I've got a PR coming up that does what this says, though I couldn't seem to get documentation to [generate the helpful note](https://github.com/rust-lang/rust/issues/43781#issuecomment-568829501) that says:

> This is only available with the "jitter" feature enabled.

<details open>

<summary>The dependency tree with `--no-default-features --features "jitter"`:</summary>

```
governor v0.3.0-dev (/mnt/data/work/github/antifuchs/governor)
├── no-std-compat v0.4.0
│   └── hashbrown v0.6.3
│       └── ahash v0.2.18
│           └── const-random v0.1.8
│               ├── const-random-macro v0.1.8
│               │   ├── getrandom v0.1.14
│               │   │   ├── cfg-if v0.1.10
│               │   │   └── libc v0.2.70
│               │   └── proc-macro-hack v0.5.15
│               └── proc-macro-hack v0.5.15
├── nonzero_ext v0.2.0
├── parking_lot v0.10.2
│   ├── lock_api v0.3.4
│   │   └── scopeguard v1.1.0
│   └── parking_lot_core v0.7.2
│       ├── cfg-if v0.1.10
│       ├── libc v0.2.70
│       └── smallvec v1.4.0
└── rand v0.7.3
    ├── getrandom v0.1.14 (*)
    ├── libc v0.2.70
    ├── rand_chacha v0.2.2
    │   ├── ppv-lite86 v0.2.6
    │   └── rand_core v0.5.1
    │       └── getrandom v0.1.14 (*)
    └── rand_core v0.5.1 (*)
```

</details>

<details open>

<summary>Without `--features "jitter"` it's:</summary>

```
governor v0.3.0-dev (/mnt/data/work/github/antifuchs/governor)
├── no-std-compat v0.4.0
│   └── hashbrown v0.6.3
│       └── ahash v0.2.18
│           └── const-random v0.1.8
│               ├── const-random-macro v0.1.8
│               │   ├── getrandom v0.1.14
│               │   │   ├── cfg-if v0.1.10
│               │   │   └── libc v0.2.70
│               │   └── proc-macro-hack v0.5.15
│               └── proc-macro-hack v0.5.15
├── nonzero_ext v0.2.0
└── parking_lot v0.10.2
    ├── lock_api v0.3.4
    │   └── scopeguard v1.1.0
    └── parking_lot_core v0.7.2
        ├── cfg-if v0.1.10
        ├── libc v0.2.70
        └── smallvec v1.4.0
```

</details>

Hm, looks like we only save on these:

```
    ├── libc v0.2.70
    ├── rand_chacha v0.2.2
    │   ├── ppv-lite86 v0.2.6
    │   └── rand_core v0.5.1
```

haha, looks like the value is not as high as I thought. I'll submit the PR anyway, in case you think it's worth including.

### PR DESCRIPTION
**Pull request by azriel91**
Closes #31.

Feel free to close if it's not super high value -- it only saves a few dependencies as discovered while I was writing the issue :upside_down_face:.

### CODE REVIEW

**Comment by antifuchs** [comment]
This makes sense - I'm always a little worried about the complexity of introducing more features, but this seems good.

**Comment by antifuchs** [comment]
Reported as https://github.com/EmbarkStudios/cargo-deny-action/issues/16 - I think this is a github action version mismatch /:

**Comment by antifuchs** [comment]
OK, turns out I'd misconfigured the cargo_deny action; let's try this again!

**Comment by little-arhat** [comment]
@antifuchs @azriel91 seems that jitter is not fully behind feature gate:

Cargo.toml:
```
governor = {version = "0.4.2", default-features = false, features = ["std"] }
```

error:
```
error[E0432]: unresolved import `crate::Jitter`
 --> /Users/r/.cargo/registry/src/github.com-1ecc6299db9ec823/governor-0.4.2/src/state/keyed/future.rs:4:79
  |
4 |     clock, middleware::RateLimitingMiddleware, state::keyed::KeyedStateStore, Jitter, NotUntil,
  |                                                                               ^^^^^^
  |                                                                               |
  |                                                                               no `Jitter` in the root
  |                                                                               help: a similar name exists in the module: `jitter`
```

**Pull request merged**
